function y = clickTrain(...
    sampleRateHz,...
    clickRateHz,...
    durationSeconds,...
    level_dB_SPL,...
    fullScaleLevel_dB_SPL...
)
y = zeroStimulus(totalSamples(sampleRateHz, durationSeconds));
clickAmplitude = ...
    desiredRms(level_dB_SPL, fullScaleLevel_dB_SPL) /...
    unattenuatedRms(sampleRateHz, clickRateHz, durationSeconds);
y(clickIndices(sampleRateHz, clickRateHz, durationSeconds)) = clickAmplitude;
end

function N = totalSamples(rateHz, durationSeconds)
N = samples(rateHz, durationSeconds);
end

function y = unattenuatedRms(...
    sampleRateHz,...
    clickRateHz,...
    durationSeconds...
)
y = clickSignalRms(...
    clickSamples(clickRateHz, durationSeconds),...
    totalSamples(sampleRateHz, durationSeconds)...
);
end

function N = clickSamples(rateHz, durationSeconds)
N = samples(rateHz, durationSeconds);
end

function i = clickIndices(...
    sampleRateHz,...
    clickRateHz,...
    durationSeconds...
)
i = sampleRateHz/clickRateHz*(0:clickSamples(clickRateHz, durationSeconds)-1)+1;
end