function y = clickTrain(...
    sampleRateHz,...
    clickRateHz,...
    durationSeconds,...
    level_dB_SPL,...
    fullScaleLevel_dB_SPL...
)
samples = sampleRateHz * durationSeconds;
clicks = clickRateHz * durationSeconds;
unattenuatedTrainRms = sqrt(clicks/samples);
clickAmplitude = ...
    10^((level_dB_SPL - fullScaleLevel_dB_SPL)/20) / unattenuatedTrainRms;
y = zeros(samples, 1);
y(sampleRateHz/clickRateHz*(0:clicks-1)+1) = clickAmplitude;
end