function y = exampleGatedClick
sampleRateHz = 44100;
clickDurationSeconds = 0.001;
gapDurationSeconds = 0.5;
level_dB_SPL = 75;
fullScaleLevel_dB_SPL = 119;
y = gatedClick(...
    sampleRateHz,...
    clickDurationSeconds,...
    gapDurationSeconds,...
    level_dB_SPL,...
    fullScaleLevel_dB_SPL...
);
end