function y = exampleClickTrain
sampleRateHz = 44100;
clickRateHz = 30;
durationSeconds = 1;
level_dB_SPL = 75;
fullScaleLevel_dB_SPL = 119;
y = clickTrain(...
    sampleRateHz,...
    clickRateHz,...
    durationSeconds,...
    level_dB_SPL,...
    fullScaleLevel_dB_SPL...
);
end