function y = gatedClick(...
    sampleRateHz,...
    clickDurationSeconds,...
    gapDurationSeconds,...
    level_dB_SPL,...
    fullScaleLevel_dB_SPL...
)
eachClickSamples = clickDurationSeconds * sampleRateHz;
gapSamples = gapDurationSeconds * sampleRateHz;
samples = gapSamples + 2*eachClickSamples;
unattenuatedRms = sqrt(2*eachClickSamples/samples);
clickAmplitude = ...
    10^((level_dB_SPL - fullScaleLevel_dB_SPL)/20) / unattenuatedRms;
y = zeros(samples, 1);
y(1:eachClickSamples) = clickAmplitude;
y(end-eachClickSamples+1:end) = clickAmplitude;
end